services:
  grafana:
    extends:
      file: .config/docker-compose-base.yaml
      service: grafana
    ports:
      - "3001:3000"
    volumes:
      - ./dist:/var/lib/grafana/plugins/mindking-site-manager-dashboard
      - ./provisioning:/etc/grafana/provisioning
    environment:
      GF_PLUGINS_ALLOW_LOADING_UNSIGNED_PLUGINS: mindking-site-manager-dashboard
      GF_PLUGINS_SKIP_PLUGIN_CHECK: "true"
      GF_PATHS_PLUGINS: /var/lib/grafana/plugins
