services:
  grafana:
    user: root
    container_name: 'mindking-hive-selector-app'

    build:
      context: .
      args:
        grafana_image: ${GRAFANA_IMAGE:-grafana-enterprise}
        grafana_version: ${GRAFANA_VERSION:-12.2.1}
        development: ${DEVELOPMENT:-false}
        anonymous_auth_enabled: ${ANONYMOUS_AUTH_ENABLED:-true}
    ports:
      - 3001:3000/tcp
    volumes:
      - ../dist:/var/lib/grafana/plugins/mindking-site-manager-dashboard
      - ../provisioning:/etc/grafana/provisioning
      - ..:/root/mindking-hive-selector-app

    environment:
      NODE_ENV: development
      GF_LOG_FILTERS: plugin.mindking-site-manager-dashboard:debug
      GF_LOG_LEVEL: debug
      GF_DATAPROXY_LOGGING: 1
      GF_PLUGINS_ALLOW_LOADING_UNSIGNED_PLUGINS: mindking-site-manager-dashboard